// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4W2Hme5anCb3VTJHSid6i_EbKkRWXns',
    appId: '1:551758957173:web:036d113db45ab173b7463c',
    messagingSenderId: '551758957173',
    projectId: 'musika-bd64b',
    authDomain: 'musika-bd64b.firebaseapp.com',
    storageBucket: 'musika-bd64b.appspot.com',
    measurementId: 'G-8QM5CE8T5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5rfHtrJIGX5QWbvLHb3ogtWnZsIkdcM',
    appId: '1:551758957173:android:2280646769a7338db7463c',
    messagingSenderId: '551758957173',
    projectId: 'musika-bd64b',
    storageBucket: 'musika-bd64b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe4W2Hme5anCb3VTJHSid6i_EbKkRWXns',
    appId: '1:551758957173:web:ffd66ab635ce99d6b7463c',
    messagingSenderId: '551758957173',
    projectId: 'musika-bd64b',
    authDomain: 'musika-bd64b.firebaseapp.com',
    storageBucket: 'musika-bd64b.appspot.com',
    measurementId: 'G-LK49659XZV',
  );
}
